spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASEURL:jdbc:mysql://localhost:3307/financial_info}
    username: ${DBUSERNAME:root}
    password: ${DBPASSWORD:root}


